package VISTA;

import javaapplication59.Conexion;
import MODELO.Alumno;
import MODELO.Materia;
import CONTROLADOR.AlumnoData;
import CONTROLADOR.CursadaData;
import CONTROLADOR.MateriaData;
import MODELO.Cursada1;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * @author Sergio
 */
public class AlumnosMateriav extends javax.swing.JInternalFrame {
  public  DefaultTableModel modelo;
  public  ArrayList<Cursada1>listaCursada;
  public  ArrayList<Materia>listaMaterias;
  public  CursadaData cursadaData;
  public  MateriaData materiaData;
  public  AlumnoData alumnoData;
  public  ArrayList<Alumno>listaAlumnos;
  public  Conexion conexion;
    /**
     * Creates new form AlumnosMateriav
     */
    public AlumnosMateriav() {
        initComponents();
      try {
          conexion=new Conexion();
      } catch (ClassNotFoundException ex) {
          System.out.println("error en conexion");
      }
      modelo=new DefaultTableModel();
      
      cursadaData=new CursadaData(conexion);
      listaCursada=(ArrayList)cursadaData.obtenerCursadas();
    
      materiaData=new MateriaData(conexion);
      listaMaterias=(ArrayList)materiaData.obtenerMaterias();
    
      alumnoData=new AlumnoData(conexion);
      listaAlumnos=(ArrayList)alumnoData.obtenerAlumnos();
      
      cargarMaterias();
      armarCabeceraTabla();
      borrarFilasTablas();
      cargaDatos();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMateria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlumnos = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("-LISTADO DE ALUMNOS POR MATERIA");

        jLabel2.setText("MATERIA");

        cbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriaActionPerformed(evt);
            }
        });

        tAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateriaActionPerformed
      cargaDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateriaActionPerformed

    public void cargaDatos(){
        borrarFilasTablas();
        
        Materia mat=(Materia)cbMateria.getSelectedItem();
        for(Cursada1 m:listaCursada){
            if(m.getMateria().getId()== mat.getId()){
                modelo.addRow(new Object[]{m.getAlumno().getId(),m.getAlumno().getNombre(),m.getNota()});   
            }
        }
    }
    public void borrarFilasTablas(){
    int a=modelo.getRowCount()-1;
    for(int i=a;i>=0;i--){
        modelo.removeRow(i);
    }
}
    public void armarCabeceraTabla(){
    ArrayList<Object> columns=new ArrayList<Object>();
    columns.add("ID");
    columns.add("Nombre");
    columns.add("Nota");
    for(Object it:columns){
        modelo.addColumn(it);
    }
    tAlumnos.setModel(modelo);
}

public void cargarMaterias(){
    for(Materia item:listaMaterias){
        cbMateria.addItem(item);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Materia> cbMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tAlumnos;
    // End of variables declaration//GEN-END:variables
}
